version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432"
  backend:
    build:
      context: ./
      args:
        UID: ${UID:-1001}
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    user: rails
  frontend:
    build:
      context: ../latinlearninghub-frontend
      args:
        UID: ${UID:-1001}
    volumes:
      - ../latinlearninghub-frontend:/usr/src/app
    ports:
      - "3000:3000"
    user: frontend
